package xmlreader;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.util.*;
import java.io.File;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.DocumentBuilder;
import org.w3c.dom.Document;
import org.w3c.dom.NodeList;
import org.w3c.dom.Node;

public class XMLReader {

    private static void printNode(Node node, List<String> desiredFields) {
        if (node.getNodeType() == Node.ELEMENT_NODE) {
            String nodeName = node.getNodeName();
            if (desiredFields.contains(nodeName)) {
                String nodeValue = node.getTextContent().trim();
                System.out.println(nodeName + ": " + nodeValue);
            }
            NodeList nodeList = node.getChildNodes();
            for (int i = 0; i < nodeList.getLength(); i++) {
                printNode(nodeList.item(i), desiredFields);
            }
        }
    }

    public static void main(String[] args) throws Exception {
        if (args.length == 0) {
            System.out.println("Usage: java XMLReader [field1] [field2] ...");
            return;
        }
        List<String> desiredFields = Arrays.asList(args);
        File inputFile = new File("input.xml");
        DocumentBuilderFactory dbFactory = DocumentBuilderFactory.newInstance();
        DocumentBuilder dBuilder = dbFactory.newDocumentBuilder();
        Document doc = dBuilder.parse(inputFile);
        doc.getDocumentElement().normalize();
        printNode(doc.getDocumentElement(), desiredFields);
    }
    
}
