package xmlreader;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import java.io.File;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.DocumentBuilder;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;
import org.w3c.dom.Node;

public class XMLReader {

    public static void main(String[] args) {
        try {
            // load the XML file
            File xmlFile = new File("data.xml");
            DocumentBuilderFactory dbFactory = DocumentBuilderFactory.newInstance();
            DocumentBuilder dBuilder = dbFactory.newDocumentBuilder();
            Document doc = dBuilder.parse(xmlFile);
    
            // normalize the document
            doc.getDocumentElement().normalize();
    
            // get the root element
            Element root = doc.getDocumentElement();
            System.out.println("Root element: " + root.getNodeName());
    
            // loop through child elements
            NodeList nodeList = root.getChildNodes();
            for (int i = 0; i < nodeList.getLength(); i++) {
                Node node = nodeList.item(i);
                if (node != null && node.getNodeType() == Node.ELEMENT_NODE) {
                    String nodeName = node.getNodeName();
                    String nodeValue = node.getTextContent();
                    System.out.println(nodeName + ": " + nodeValue);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
}
